### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kidonng** [kidonng/sachan#1]
- [ ] [dogbin](https://del.dog)
- [ ] Support inline mode
- [ ] Split t.cn & U.NU
  - [ ] U.NU custom path
